# Generated by Django 3.2.6 on 2021-10-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flea_market', '0004_alter_category_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
