# Generated by Django 3.2.6 on 2021-10-11 21:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flea_market', '0007_alter_ad_date_up'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='date_up',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
