# Generated by Django 3.2.6 on 2021-10-12 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flea_market', '0009_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='flea_market.region'),
            preserve_default=False,
        ),
    ]
