# Generated by Django 3.2.6 on 2021-10-29 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flea_market', '0011_ad_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='description',
            field=models.TextField(verbose_name='Описание объявления'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='type_ad',
            field=models.CharField(max_length=15, verbose_name='Тип объявления'),
        ),
    ]
