# Generated by Django 3.2.6 on 2021-10-29 02:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flea_market', '0012_auto_20211029_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flea_market.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flea_market.region', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='ad',
            name='date_up',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='ad',
            name='date_update',
            field=models.DateTimeField(auto_now=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='ad',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото'),
        ),
    ]
