# Generated by Django 3.2.6 on 2021-10-30 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flea_market', '0015_alter_ad_type_ad'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='bargain',
            field=models.BooleanField(default=False, verbose_name='Торг'),
        ),
        migrations.AddField(
            model_name='ad',
            name='price',
            field=models.FloatField(default=0, verbose_name='Цена'),
        ),
    ]
