# Generated by Django 3.2.6 on 2021-10-30 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flea_market', '0016_auto_20211030_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='short_description',
            field=models.TextField(default='', max_length=200, verbose_name='Короткое описание'),
            preserve_default=False,
        ),
    ]
