# Generated by Django 3.2.6 on 2021-11-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flea_market', '0017_ad_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='short_description',
            field=models.TextField(max_length=200, verbose_name='Короткое описание (200 символов)'),
        ),
    ]
