# Generated by Django 3.2.6 on 2021-11-05 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flea_market', '0019_auto_20211105_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='photo',
        ),
        migrations.AddField(
            model_name='image',
            name='ad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flea_market.ad'),
        ),
    ]
