# Generated by Django 3.2.6 on 2021-12-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flea_market', '0022_alter_image_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Заголовок'),
        ),
    ]
