# Generated by Django 3.2.6 on 2022-01-28 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flea_market', '0024_auto_20220113_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='type_ad',
            field=models.CharField(choices=[('sell', 'Продам'), ('buy', 'Куплю'), ('exchange', 'Обмен'), ('service', 'Услуга'), ('rent', 'Аренда')], default=('sell', 'Продам'), max_length=15, verbose_name='Тип объявления'),
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flea_market.ad')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
