# Generated by Django 3.2.6 on 2021-09-01 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eng', models.CharField(max_length=50)),
                ('name_rus', models.CharField(max_length=50)),
                ('abbreviated_name_eng', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PreviousExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('count', models.IntegerField()),
                ('update_date', models.DateField(auto_now_add=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange_rates.currency')),
            ],
        ),
    ]
