# Generated by Django 3.2.6 on 2021-09-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_rates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previousexchangerate',
            name='price',
            field=models.FloatField(),
        ),
    ]
