# Generated by Django 3.2.6 on 2021-09-02 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_rates', '0002_alter_previousexchangerate_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='abbreviated_name_eng',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
