# Generated by Django 3.2.6 on 2021-09-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_rates', '0003_alter_currency_abbreviated_name_eng'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='abbreviated_name_eng',
            new_name='abbreviation',
        ),
        migrations.AlterField(
            model_name='previousexchangerate',
            name='update_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
