# Generated by Django 3.2.6 on 2021-09-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_rates', '0004_auto_20210902_1833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='name_eng',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='name_rus',
        ),
        migrations.AddField(
            model_name='currency',
            name='cur_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
